config/routes.rb
Rails.application.routes.draw do
  resources :expeditions, only: [:index, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/equipment.rb
class Equipment < ApplicationRecord
    has_many :expedition_equipments
    has_many :expeditions, through: :expedition_equipments

    validates :name, presence: :true
end

app/models/expedition.rb
class Expedition < ApplicationRecord
    has_many :expedition_equipments
    has_many :equipment, through: :expedition_equipments

    accepts_nested_attributes_for :equipment

    def equipment_attributes=(equipment_attributes)
        equipment_attributes.each do |key, value|
            if !value[:name].empty?
                if new_item = Equipment.find_by(name: value[:name])
                    self.equipment << new_item
                else
                    self.equipment.build(name: value[:name])
                end
            end
        end
    end
end

app/models/expedition_equipment.rb
class ExpeditionEquipment < ApplicationRecord
  belongs_to :expedition
  belongs_to :equipment
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/expeditions_controller.rb
class ExpeditionsController < ApplicationController

    def index
        @expeditions = Expedition.all
    end

    def new
        @expedition = Expedition.new
        3.times do
            @expedition.equipment.build
        end
        @equipment = Equipment.all
    end

    def create
        @expedition = Expedition.new(expedition_params)
        if @expedition.save
            redirect_to expeditions_path
        else
            render :new
        end
    end

    private

        def expedition_params
            params.require(:expedition).permit(:name, :description, :length, :difficulty, equipment_ids: [], equipment_attributes: [:name])
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/expeditions/index.html.erb
<h1>All My Expeditions</h1>

<%= link_to "Create New Expedition", new_expedition_path %>

<% @expeditions.each do |expedition| %>
    <div>
        <h3><%= expedition.name %></h3>
        <p><%= expedition.description %></p>
        <p>Length: <%= expedition.length %> KM</p>
        <p>Difficulty: <%= expedition.difficulty %></p>
        <% if expedition.equipment.count > 0 %>
            <p>Required Equipment</p>
            <ul>
                <% expedition.equipment.each do |equipment| %>
                    <li><%= equipment.name %></li>
                <% end %>
            </ul>
        <% end %>
    </div>
<% end %>

app/views/expeditions/new.html.erb
<h2>New Expedition Form</h2>

<%= form_for @expedition do |f| %>
    <div>
        <%= f.label :name %>
        <div>
            <%= f.text_field :name %>
        </div>
    </div>
    <div>
        <%= f.label :description %>
        <div>
            <%= f.text_area :description %>
        </div>
    </div>
    <div>
        <%= f.label :length %>
        <div>
            <%= f.number_field :length, step: 0.01 %>
        </div>
    </div>
    <div>
        <%= f.label :difficulty %>
        <div>
            <%= f.text_field :difficulty %>
        </div>
    </div>

    <!-- Collection of checkboxes for equipment ids -->
    <div>
        <%= f.label "Select Equipment" %>
        <div>
            <%= f.collection_check_boxes :equipment_ids, @equipment, :id, :name %>
        </div>
    </div>

    <!-- 3 New Equipment Fields -->
    <%= f.fields_for :equipment do |equipment_fields| %>
        <%= equipment_fields.label :name %>
        <div>
            <%= equipment_fields.text_field :name %>
        </div>
    <% end %>

    <%= f.submit "Create Expedition" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExpeditionMaker2017</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>